spring:
  application:
    name: LearnJava_JC

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5439/SpringSecurityOauth
    username: postgres
    password: root

  liquibase:
    enabled: true
#    drop-first: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: public

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 399787504942-3him3683k21q9ajlmmmaijcdtl9lo8gq.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

logging:
  file:
    name: logs/app.log
#  level:
#    root: info
#    web: info
#    sql: debug