spring:
  application:
    name: LearnJava_JC

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5439/SpringSecurityJwt
    username: postgres
    password: root

  liquibase:
    enabled: true
#    drop-first: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: public

springdoc:
  swagger-ui:
    path: /doc

logging:
  file:
    name: logs/app.log
  level:
#    root: info
    web: info
#    sql: debug

server:
  ssl:
    key-store: classpath:mykeystore.jks
    key-store-password: qwerty
    key-password: qwerty
    key-alias: mykey
  port: